import com.inductiveautomation.ignition.common.QualifiedPath;
import com.unsautomation.ignition.piintegration.piwebapi.ApiException;
import com.unsautomation.ignition.piintegration.piwebapi.PIWebApiClient;
import com.unsautomation.ignition.piintegration.piwebapi.UrlUtils;
import com.unsautomation.ignition.piintegration.piwebapi.WebIdUtils;
import org.apache.commons.lang3.time.DateUtils;
import org.joda.time.DateTime;
import org.junit.Test;

import java.util.Date;
import java.util.Map;

public class PIWebApiTests {

    PIWebApiClient c;

    public PIWebApiTests() throws ApiException {
        c = new PIWebApiClient("https://192.168.1.213/piwebapi/", "t", "t", false, true);
    }

    @Test
    public void testAFServerWebID() throws Exception {
        var test = "Assets/DESKTOP-M7O4A7D";
        var d0 = WebIdUtils.toWebID(test);
        var r0 = c.getAssetServer().getAssetDatabases(d0, "Items.Name");
        if (r0.size() < 1) {
            throw new Exception("AF Server not found");
        }
    }

    @Test
    public void testAFDBWebID() throws Exception {
        var test = "Assets/DESKTOP-M7O4A7D/Database2";
        var d1 = WebIdUtils.toWebID(test);
        var r1 = c.getAssetDatabase().getElements(d1);
        System.out.print(r1);
        if (r1.size() < 1) {
            throw new Exception("AF Server not found");
        }
    }

    @Test
    public void testAFElementWebID() throws Exception {
        var test = "Assets/DESKTOP-M7O4A7D/Database2/Element1";
        var d1 = WebIdUtils.toWebID(test);
        var r1 = c.getElementApi().getElements(d1);
        System.out.print(r1);
        if (r1.size() < 1) {
            throw new Exception("AF Server not found");
        }
    }

    @Test
    public void testPIServers() throws Exception {
        var r1 = c.getDataServer().list(null);
        System.out.print(r1);
        if (r1.size() < 1) {
            throw new Exception("AF Server not found");
        }
    }

    @Test
    public void testListPITags() throws Exception {
        var test = "Points/DESKTOP-M7O4A7D";
        var d1 = WebIdUtils.toWebID(test);
        var r1 = c.getDataServer().getPoints(d1, null,0,1000,null);
        System.out.print(r1);
        if (r1.size() < 1) {
            throw new Exception("PI Tags not returned.....");
        }
    }

    /***
     * Test that values are in range and the correct number to events are returned???
     * @throws Exception
     */
    @Test
    public void testGetStream1() throws Exception {
        var test = "Points/DESKTOP-M7O4A7D/PI Tag";
        var startTime = DateUtils.addHours(new Date(), -1);
        var endTime = new Date();
        var d1 = WebIdUtils.toWebID(test);
        var r1 = c.getStream().getPlot(d1, startTime,endTime,100l, null,null, null);
        var size = r1.size();

        if (size < 1) {
            throw new Exception("AF Server not found");
        }
    }

    @Test
    public void testGetStreamRaw() throws Exception {
        var test = "Points/DESKTOP-M7O4A7D/PI Tag";
        var startTime = DateUtils.addHours(new Date(), -1);
        var endTime = new Date();
        var d1 = WebIdUtils.toWebID(test);
        var r1 = c.getStream().getRecorded(d1, startTime,endTime,null,null, null);

        var size = r1.getContent().getAsJsonArray("Items").size();

        if (size < 1) {
            throw new Exception("AF Server not found");
        }
    }

    @Test
    public void testUrlParameters() throws Exception {

        var x = UrlUtils.addUrlParameter("https://url/weburl", "test", "Prut");
        if (!x.equals("https://url/weburl?test=Prut")) {
            throw new Exception("Invalid Url generated by apiClient.addUrlParameter 1");
        }

        x = UrlUtils.addUrlParameter("https://url/weburl?", "test", "Prut");
        if (!x.equals("https://url/weburl?test=Prut")) {
            throw new Exception("Invalid Url generated by apiClient.addUrlParameter 2");
        }

        x = UrlUtils.addUrlParameter("https://url/weburl?x=y", "test", "Prut");
        if (!x.equals("https://url/weburl?x=y&test=Prut")) {
            throw new Exception("Invalid Url generated by apiClient.addUrlParameter 3");
        }

        x = UrlUtils.addUrlParameter("https://url/weburl?x=y&", "test", "Prut");
        if (!x.equals("https://url/weburl?x=y&test=Prut")) {
            throw new Exception("Invalid Url generated by apiClient.addUrlParameter 4");
        }
    }

    @Test
    public void testUrlParameters2() throws Exception {

        var url = "https://url/weburl";
        var parameters = Map.of(
                "nameFilter","a",
                "startIndex", "b",
                "maxCount", "c");
        url = UrlUtils.addUrlParameters(url, parameters);

      /*  if (!url.equals("https://url/weburl?nameFilter=a&startIndex=b&maxCount=c")) {
            throw new Exception("Invalid Url generated by apiClient.addUrlParameter 4");
        } */
    }

    // Test that attributes can be returned in Plot
    // Check that we have attributes encoded with a @
    // check that a attribute that starts with @ works.
}
